# Generated by Django 6.0.6 on 2026-07-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="AuthCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            (
                                "email_verification",
                                "E-posta doğrulama",
                            ),
                            ("password_reset", "Parola sıfırlama"),
                        ],
                        max_length=32,
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                (
                    "failed_attempts",
                    models.PositiveIntegerField(default=0),
                ),
                ("resend_available_at", models.DateTimeField()),
                (
                    "consumed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(consumed_at__isnull=True),
                        fields=("user", "purpose"),
                        name="users_authcode_one_unconsumed_per_purpose",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(failed_attempts__gte=0),
                        name=(
                            "users_authcode_failed_attempts_nonnegative"
                        ),
                    ),
                ],
            },
        ),
    ]
