# Generated by Django 6.0.6 on 2026-07-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoscowScopeAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("result", models.JSONField()),
                ("prompt_version", models.CharField(default="moscow-v1", max_length=50)),
                ("provider", models.CharField(blank=True, max_length=100)),
                ("model_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("idea", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="moscow_scope_analysis", to="ideas.idea")),
            ],
        ),
    ]
