# Generated by Django 6.0.6 on 2026-07-25 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0003_knowledgesource_knowledgechunk'),
        ('ideas', '0003_idea_problem_solution_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewee_name', models.CharField(blank=True, max_length=255)),
                ('interviewee_profile', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField()),
                ('interviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_notes', to='ideas.idea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
