# Generated by Django 6.0.6 on 2026-07-26 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0004_interviewnote'),
        ('ideas', '0004_riskyassumptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEvidenceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField()),
                ('prompt_version', models.CharField(default='interview-evidence-v1', max_length=50)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_evidence_analyses', to='ideas.idea')),
                ('interview_notes', models.ManyToManyField(related_name='evidence_analyses', to='analyses.interviewnote')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
