# Generated by Django 6.0.6 on 2026-07-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="problem",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="idea",
            name="solution",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="idea",
            name="sector_category",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="ValidationRoadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roadmap_data",
                    models.JSONField(default=dict),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "idea",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_roadmap",
                        to="ideas.idea",
                    ),
                ),
            ],
        ),
    ]
