# Generated by Django 6.0.6 on 2026-07-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_competitoranalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='rag_sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
