# Generated by Django 6.0.6 on 2026-07-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_idea_rag_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorPitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_pitch', to='ideas.idea')),
            ],
        ),
    ]
